services:
    - type: web
    name: ezed-x-tech
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: session-disk
      mountPath: /opt/render/project/src/session
      sizeGB: 1
